name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install --yes shellcheck

      - name: Run lint target
        run: make lint
